language: matlab

services:
  - docker

jobs:
  include:
    - name: InfluxDB v1.x
      language: matlab
      env:
        - INFLUXDB_VERSION="1.8"
      before_install:
        - >
          docker run -d -p 8086:8086
          -e INFLUXDB_ADMIN_USER=user
          -e INFLUXDB_ADMIN_PASSWORD=password
          influxdb:${INFLUXDB_VERSION}
      script:
        - matlab -batch 'run_tests'

    - name: InfluxDB v2.x
      language: matlab
      env:
        - INFLUXDB_VERSION="2.0"
      before_install:
        - >
          docker run -d -p 8086:8086
          -e DOCKER_INFLUXDB_INIT_MODE=setup
          -e DOCKER_INFLUXDB_INIT_USERNAME=user
          -e DOCKER_INFLUXDB_INIT_PASSWORD=password
          -e DOCKER_INFLUXDB_INIT_ORG=test_org
          -e DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
          -e DOCKER_INFLUXDB_INIT_RETENTION=1w
          influxdb:${INFLUXDB_VERSION}
      script:
        - matlab -batch 'run_tests'
